[[redirects]]
  from = "/res/*"
  to = "https://coderstation-api-dyxxixi.koyeb.app/res/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://coderstation-api-dyxxixi.koyeb.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/static/*"
  to = "https://coderstation-api-dyxxixi.koyeb.app/static/:splat"
  status = 200
  force = true
