[[redirects]]
  from = "/res/*"
  to = "https://coderstation-api-dyxxixi.koyeb.app/res/:splat"

[[redirects]]
  from = "/api/*"
  to = "https://coderstation-api-dyxxixi.koyeb.app/api/:splat"

[[redirects]]
  from = "/static/*"
  to = "https://coderstation-api-dyxxixi.koyeb.app/static/:splat"

[[redirects]]
  from = "/*"
  to = "index.html"
